version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/cafezinho-api
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - cafezinho-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cafezinho-api-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - integration