# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/cafezinho-api

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies
      - attach_workspace:
          - at: ~/cafezinho-api

      - restore_cache:
          keys:
            - cafezinho-api-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - cafezinho-api-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: cafezinho-api-{{ checksum "pom.xml" }}

